# -*- coding: utf-8 -*-
"""Welcome To Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import re
import ast
#module 1
def tokenize(exp):
  #regular expression
  token_pattern = r'\d+|[a-zA-Z]+|[^\s\d\w]'
  
  #tokenize expression
  tokens = re.findall(token_pattern, exp)
  return tokens

exp = 'r+[(]u*t)'
tokens = tokenize(exp)
print("Tokens = \n")
print(tokens)  
print("\n")

#module 2
#syntax tree
code=ast.parse("print('r+[(]u*t)')")

print("Syntax Tree = \n")
print(ast.dump (code)) 
exec(compile(code, filename="",mode="exec"))